### ISSUE TITLE
Conflict with NFS injector

### ISSUE THREAD

**Issue by erevos13** [iamlooper/MemeUI-Enhancer#2]
It remove essential files required for nfs pro activation and causes issues with activation..
Please look into it..

**Comment by erevos13** [comment]
aohln.txt
zdvqc.txt

Are removed by this module which disables pro activation.

**Comment by iamlooper** [comment]
> aohln.txt zdvqc.txt
> 
> Are removed by this module which disables pro activation.

MemeUI Enhancer cleans any useless trash that are present in system. The developer of NFS project should choose a sandboxed or better path to store the respective items.
