### ISSUE TITLE
Battery drain too fast

### ISSUE THREAD

**Issue by AijazAhmed420** [iamlooper/MemeUI-Enhancer#4]
MemeUI-Enhancer working fine for me expect battery
The battery just drain too fast the issue is when I am not using any task but usage of CPU is 100% I test on cpu-z app. when we don't perform any task CPU usage should be low so the battery stands a little longer.
Hope you will fix it.
Btw I am using Redmi Note 11 spes with dark mode enable and battery saver enabled.

**Comment by ANULAL2020** [comment]
> MemeUI-Enhancer working fine for me expect battery The battery just drain too fast the issue is when I am not using any task but usage of CPU is 100% I test on cpu-z app. when we don't perform any task CPU usage should be low so the battery stands a little longer. Hope you will fix it. Btw I am using Redmi Note 11 spes with dark mode enable and battery saver enabled.



Do kill the memeenhancer.sh process using FKM app.
